name: build

on:
  workflow_call:
  workflow_dispatch:

env:
  NIX_PATH: nixpkgs=channel:nixos-24.05

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - run: nix-shell --command make
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist

